# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelDiaries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelDiaries
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage'
  pod 'PureLayout'

end

#  target 'TravelDiariesTests' do
#      inherit! :search_paths
#    # Pods for testing
#    pod 'Alamofire', '~> 4.7'
#  end
